"""initial schema

Revision ID: 86b7caa82272
Revises: 
Create Date: 2026-06-18 11:34:00.179809
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = '86b7caa82272'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'live', 'closed', 'archived', name='eventstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitions',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('public_voting_enabled', sa.Boolean(), nullable=False),
    sa.Column('judge_voting_enabled', sa.Boolean(), nullable=False),
    sa.Column('public_vote_method', sa.Enum('single_choice', 'ranked_choice', 'criteria_rating', name='publicvotemethod', native_enum=False), nullable=False),
    sa.Column('public_weight', sa.Float(), nullable=False),
    sa.Column('judge_weight', sa.Float(), nullable=False),
    sa.Column('access_method', sa.Enum('public_link', 'qr_pin', 'private_link', name='accessmethod', native_enum=False), nullable=False),
    sa.Column('access_pin_hash', sa.String(length=255), nullable=True),
    sa.Column('max_votes_per_user', sa.Integer(), nullable=False),
    sa.Column('allow_vote_update', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready', 'voting_open', 'voting_closed', 'results_frozen', 'revealed', name='competitionstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_event_id'), 'competitions', ['event_id'], unique=False)
    op.create_table('judges',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('access_code_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judges_event_id'), 'judges', ['event_id'], unique=False)
    op.create_table('voter_sessions',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('voter_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_hash', sa.String(length=255), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voter_sessions_event_id'), 'voter_sessions', ['event_id'], unique=False)
    op.create_index(op.f('ix_voter_sessions_voter_token_hash'), 'voter_sessions', ['voter_token_hash'], unique=False)
    op.create_table('competition_judges',
    sa.Column('competition_id', sa.String(), nullable=False),
    sa.Column('judge_id', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'judge_id')
    )
    op.create_index(op.f('ix_competition_judges_competition_id'), 'competition_judges', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_judges_judge_id'), 'competition_judges', ['judge_id'], unique=False)
    op.create_table('judge_criteria',
    sa.Column('competition_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judge_criteria_competition_id'), 'judge_criteria', ['competition_id'], unique=False)
    op.create_table('participants',
    sa.Column('competition_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('performance_title', sa.String(length=255), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_competition_id'), 'participants', ['competition_id'], unique=False)
    op.create_table('public_vote_criteria',
    sa.Column('competition_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_vote_criteria_competition_id'), 'public_vote_criteria', ['competition_id'], unique=False)
    op.create_table('result_snapshots',
    sa.Column('competition_id', sa.String(), nullable=False),
    sa.Column('snapshot_name', sa.String(length=255), nullable=False),
    sa.Column('results_json', sa.JSON(), nullable=False),
    sa.Column('created_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_snapshots_competition_id'), 'result_snapshots', ['competition_id'], unique=False)
    op.create_table('screen_states',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('competition_id', sa.String(), nullable=True),
    sa.Column('mode', sa.Enum('idle', 'show_qr', 'voting_open', 'countdown', 'show_results', 'reveal_ranking', 'show_podium', 'show_final_winners', name='screenmode', native_enum=False), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'competition_id')
    )
    op.create_index(op.f('ix_screen_states_competition_id'), 'screen_states', ['competition_id'], unique=False)
    op.create_index(op.f('ix_screen_states_event_id'), 'screen_states', ['event_id'], unique=False)
    op.create_table('voting_sessions',
    sa.Column('competition_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', 'cancelled', name='votingsessionstatus', native_enum=False), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('closed_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voting_sessions_competition_id'), 'voting_sessions', ['competition_id'], unique=False)
    op.create_table('judge_votes',
    sa.Column('competition_id', sa.String(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('judge_id', sa.String(), nullable=False),
    sa.Column('voting_session_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voting_session_id'], ['voting_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'judge_id', 'voting_session_id')
    )
    op.create_index(op.f('ix_judge_votes_competition_id'), 'judge_votes', ['competition_id'], unique=False)
    op.create_index(op.f('ix_judge_votes_judge_id'), 'judge_votes', ['judge_id'], unique=False)
    op.create_index(op.f('ix_judge_votes_participant_id'), 'judge_votes', ['participant_id'], unique=False)
    op.create_index(op.f('ix_judge_votes_voting_session_id'), 'judge_votes', ['voting_session_id'], unique=False)
    op.create_table('public_votes',
    sa.Column('competition_id', sa.String(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('voting_session_id', sa.String(), nullable=False),
    sa.Column('voter_session_id', sa.String(), nullable=False),
    sa.Column('vote_method', sa.Enum('single_choice', 'ranked_choice', 'criteria_rating', name='publicvotemethod', native_enum=False), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_session_id'], ['voter_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voting_session_id'], ['voting_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_votes_competition_id'), 'public_votes', ['competition_id'], unique=False)
    op.create_index(op.f('ix_public_votes_participant_id'), 'public_votes', ['participant_id'], unique=False)
    op.create_index(op.f('ix_public_votes_voter_session_id'), 'public_votes', ['voter_session_id'], unique=False)
    op.create_index(op.f('ix_public_votes_voting_session_id'), 'public_votes', ['voting_session_id'], unique=False)
    op.create_table('judge_criterion_votes',
    sa.Column('judge_vote_id', sa.String(), nullable=False),
    sa.Column('criterion_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['judge_criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_vote_id'], ['judge_votes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('judge_vote_id', 'criterion_id')
    )
    op.create_index(op.f('ix_judge_criterion_votes_criterion_id'), 'judge_criterion_votes', ['criterion_id'], unique=False)
    op.create_index(op.f('ix_judge_criterion_votes_judge_vote_id'), 'judge_criterion_votes', ['judge_vote_id'], unique=False)
    op.create_table('public_criterion_votes',
    sa.Column('public_vote_id', sa.String(), nullable=False),
    sa.Column('criterion_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['public_vote_criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['public_vote_id'], ['public_votes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_vote_id', 'criterion_id')
    )
    op.create_index(op.f('ix_public_criterion_votes_criterion_id'), 'public_criterion_votes', ['criterion_id'], unique=False)
    op.create_index(op.f('ix_public_criterion_votes_public_vote_id'), 'public_criterion_votes', ['public_vote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_criterion_votes_public_vote_id'), table_name='public_criterion_votes')
    op.drop_index(op.f('ix_public_criterion_votes_criterion_id'), table_name='public_criterion_votes')
    op.drop_table('public_criterion_votes')
    op.drop_index(op.f('ix_judge_criterion_votes_judge_vote_id'), table_name='judge_criterion_votes')
    op.drop_index(op.f('ix_judge_criterion_votes_criterion_id'), table_name='judge_criterion_votes')
    op.drop_table('judge_criterion_votes')
    op.drop_index(op.f('ix_public_votes_voting_session_id'), table_name='public_votes')
    op.drop_index(op.f('ix_public_votes_voter_session_id'), table_name='public_votes')
    op.drop_index(op.f('ix_public_votes_participant_id'), table_name='public_votes')
    op.drop_index(op.f('ix_public_votes_competition_id'), table_name='public_votes')
    op.drop_table('public_votes')
    op.drop_index(op.f('ix_judge_votes_voting_session_id'), table_name='judge_votes')
    op.drop_index(op.f('ix_judge_votes_participant_id'), table_name='judge_votes')
    op.drop_index(op.f('ix_judge_votes_judge_id'), table_name='judge_votes')
    op.drop_index(op.f('ix_judge_votes_competition_id'), table_name='judge_votes')
    op.drop_table('judge_votes')
    op.drop_index(op.f('ix_voting_sessions_competition_id'), table_name='voting_sessions')
    op.drop_table('voting_sessions')
    op.drop_index(op.f('ix_screen_states_event_id'), table_name='screen_states')
    op.drop_index(op.f('ix_screen_states_competition_id'), table_name='screen_states')
    op.drop_table('screen_states')
    op.drop_index(op.f('ix_result_snapshots_competition_id'), table_name='result_snapshots')
    op.drop_table('result_snapshots')
    op.drop_index(op.f('ix_public_vote_criteria_competition_id'), table_name='public_vote_criteria')
    op.drop_table('public_vote_criteria')
    op.drop_index(op.f('ix_participants_competition_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_judge_criteria_competition_id'), table_name='judge_criteria')
    op.drop_table('judge_criteria')
    op.drop_index(op.f('ix_competition_judges_judge_id'), table_name='competition_judges')
    op.drop_index(op.f('ix_competition_judges_competition_id'), table_name='competition_judges')
    op.drop_table('competition_judges')
    op.drop_index(op.f('ix_voter_sessions_voter_token_hash'), table_name='voter_sessions')
    op.drop_index(op.f('ix_voter_sessions_event_id'), table_name='voter_sessions')
    op.drop_table('voter_sessions')
    op.drop_index(op.f('ix_judges_event_id'), table_name='judges')
    op.drop_table('judges')
    op.drop_index(op.f('ix_competitions_event_id'), table_name='competitions')
    op.drop_table('competitions')
    op.drop_table('events')
    # ### end Alembic commands ###
